# Generated by Django 5.1 on 2026-03-22 15:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du plat (max 200 caracteres)', max_length=200, verbose_name='Nom du plat')),
                ('description', models.TextField(blank=True, help_text='Description detaillee du plat', null=True, verbose_name='Description')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Prix en GNF (Francs Guineens)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix unitaire')),
                ('image', models.ImageField(blank=True, help_text='Image du plat (formats acceptes: JPG, PNG)', null=True, upload_to='plats/%Y/%m/', verbose_name='Image du plat')),
                ('disponible', models.BooleanField(default=True, help_text='Le plat est-il disponible a la commande ?', verbose_name='Disponible')),
                ('categorie', models.CharField(choices=[('ENTREE', 'Entree'), ('PLAT', 'Plat principal'), ('DESSERT', 'Dessert'), ('BOISSON', 'Boisson'), ('ACCOMPAGNEMENT', 'Accompagnement')], default='PLAT', max_length=20, verbose_name='Categorie')),
                ('necessite_validation_cuisine', models.BooleanField(default=False, help_text="Si True : la commande doit passer par l'etape PRETE (un cuisinier valide la preparation) avant d'etre servie. Si False : le serveur peut servir directement.", verbose_name='Necessite validation cuisine')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Derniere modification')),
            ],
            options={
                'verbose_name': 'Plat',
                'verbose_name_plural': 'Plats',
                'ordering': ['categorie', 'nom'],
                'indexes': [models.Index(fields=['disponible', 'categorie'], name='menu_plat_disponi_1437c2_idx'), models.Index(fields=['nom'], name='menu_plat_nom_e3daf3_idx')],
            },
        ),
    ]
