# Generated by Django 5.1 on 2026-06-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL d'image externe (prioritaire sur le fichier uploade) — utile pour les demos", max_length=500, null=True, verbose_name="URL d'image externe"),
        ),
    ]
