# Generated by Django 5.1 on 2026-03-22 15:41

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('login', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('Rtable', 'Table'), ('Rserveur', 'Serveur'), ('Rchef_cuisinier', 'Chef Cuisinier'), ('Rcuisinier', 'Cuisinier'), ('Rcomptable', 'Comptable'), ('Radmin', 'Administrateur')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('nom_complet', models.CharField(blank=True, help_text='Obligatoire pour tous les roles sauf Rtable', max_length=200, null=True, verbose_name='Nom complet')),
                ('email', models.EmailField(blank=True, help_text='Obligatoire pour tous les roles sauf Rtable', max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Adresse email')),
                ('telephone', models.CharField(blank=True, help_text='Obligatoire pour tous les roles sauf Rtable', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format valide: +224XXXXXXXXX ou XXXXXXXXX (9-20 chiffres)', regex='^\\+?[0-9]{9,20}$')], verbose_name='Numero de telephone')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'user',
            },
        ),
    ]
