# Generated by Django 5.1 on 2026-04-09 16:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Obligatoire pour tous les rôles sauf Rtable — unique sur toute la plateforme', max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Forcé à True à la création — reset à False après changement', verbose_name='Doit changer le mot de passe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nom_complet',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Rsuper_admin', 'Super Administrateur'), ('Radmin', 'Administrateur'), ('Rmanager', 'Manager'), ('Rserveur', 'Serveur'), ('Rchef_cuisinier', 'Chef Cuisinier'), ('Rcuisinier', 'Cuisinier'), ('Rcomptable', 'Comptable'), ('Rtable', 'Table')], max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format valide: +224XXXXXXXXX ou XXXXXXXXX (9-20 chiffres)', regex='^\\+?[0-9]{9,20}$')], verbose_name='Numéro de téléphone'),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token')),
                ('expires_at', models.DateTimeField(verbose_name='Expiration')),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Token de réinitialisation',
                'verbose_name_plural': 'Tokens de réinitialisation',
                'ordering': ['-created_at'],
            },
        ),
    ]
