# Generated by Django 5.1 on 2026-06-24 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_must_change_password_and_more'),
        ('company', '0002_onboardingtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=100, verbose_name='Libellé')),
                ('categorie', models.CharField(max_length=50, verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permission',
                'ordering': ['categorie', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RoleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du rôle')),
                ('slug', models.CharField(help_text='Identifiant court lisible (ex: Radmin, Rserveur)', max_length=30, verbose_name='Slug')),
                ('is_system', models.BooleanField(default=False, help_text='Rôle système — non modifiable par les admins', verbose_name='Rôle système')),
                ('dashboard_type', models.CharField(choices=[('admin', 'Dashboard Admin / Manager'), ('serveur', 'Dashboard Serveur'), ('cuisine', 'Dashboard Cuisine'), ('comptable', 'Dashboard Comptable')], default='admin', max_length=20, verbose_name='Type de dashboard')),
                ('permissions', models.ManyToManyField(blank=True, related_name='role_configs', to='accounts.permission', verbose_name='Permissions')),
                ('restaurant', models.ForeignKey(blank=True, help_text='Null pour les rôles système globaux', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_configs', to='company.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Configuration de rôle',
                'verbose_name_plural': 'Configurations de rôles',
                'db_table': 'role_config',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role_config',
            field=models.ForeignKey(blank=True, help_text='Null pour Rsuper_admin et Rtable (rôles structurels)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.roleconfig', verbose_name='Configuration de rôle'),
        ),
    ]
