# Generated by Django 5.1 on 2026-06-24 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_manage_tables_to_manager'),
        ('company', '0004_rclient_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Null pour Rsuper_admin et Rclient (pas liés à un restaurant)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='company.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Rsuper_admin', 'Super Administrateur'), ('Radmin', 'Administrateur'), ('Rmanager', 'Manager'), ('Rserveur', 'Serveur'), ('Rchef_cuisinier', 'Chef Cuisinier'), ('Rcuisinier', 'Cuisinier'), ('Rcomptable', 'Comptable'), ('Rtable', 'Table'), ('Rclient', 'Client')], max_length=20, verbose_name='Rôle'),
        ),
    ]
