# Generated by Django 5.1 on 2026-07-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_deactivate_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleconfig',
            name='dashboard_type',
            field=models.CharField(choices=[('admin', 'Dashboard Admin / Manager'), ('serveur', 'Dashboard Serveur'), ('cuisine', 'Dashboard Cuisine'), ('comptable', 'Dashboard Comptable'), ('livreur', 'Dashboard Livreur')], default='admin', max_length=20, verbose_name='Type de dashboard'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Rsuper_admin', 'Super Administrateur'), ('Radmin', 'Administrateur'), ('Rmanager', 'Manager'), ('Rserveur', 'Serveur'), ('Rchef_cuisinier', 'Chef Cuisinier'), ('Rcuisinier', 'Cuisinier'), ('Rcomptable', 'Comptable'), ('Rlivreur', 'Livreur'), ('Rtable', 'Table'), ('Rclient', 'Client')], max_length=20, verbose_name='Rôle'),
        ),
    ]
