# Generated by Django 5.1 on 2026-07-23 13:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_validate_approvisionnement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdresseClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex. : Maison, Bureau, Chez maman', max_length=50, verbose_name='Libellé')),
                ('description', models.TextField(help_text='Repère de livraison (ex. « en face de la pharmacie X, portail bleu »)', verbose_name='Adresse / point de repère')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('telephone', models.CharField(blank=True, help_text='Optionnel — contact spécifique à ce lieu, sinon celui du compte', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format valide: +224XXXXXXXXX ou XXXXXXXXX (9-20 chiffres)', regex='^\\+?[0-9]{9,20}$')], verbose_name='Téléphone du lieu')),
                ('is_default', models.BooleanField(default=False, verbose_name='Adresse par défaut')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Adresse client',
                'verbose_name_plural': 'Adresses client',
                'db_table': 'adresse_client',
                'ordering': ['-is_default', '-date_creation'],
            },
        ),
    ]
