# Generated by Django 5.1 on 2026-08-25 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_adresseclient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adresseclient",
            name="telephone",
            field=models.CharField(
                blank=True,
                help_text="Optionnel - contact spécifique à ce lieu, sinon celui du compte",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Format valide: +224XXXXXXXXX ou XXXXXXXXX (9-20 chiffres)",
                        regex="^\\+?[0-9]{9,20}$",
                    )
                ],
                verbose_name="Téléphone du lieu",
            ),
        ),
        migrations.AlterField(
            model_name="roleconfig",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="Rôle système - non modifiable par les admins",
                verbose_name="Rôle système",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Obligatoire pour tous les rôles sauf Rtable - unique sur toute la plateforme",
                max_length=254,
                null=True,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Adresse email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="Forcé à True à la création - reset à False après changement",
                verbose_name="Doit changer le mot de passe",
            ),
        ),
    ]
