# Generated by Django 5.1 on 2026-03-22 15:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_table', models.CharField(max_length=10, unique=True, verbose_name='Numero de table')),
                ('nombre_places', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de places')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'Rtable'}, on_delete=django.db.models.deletion.CASCADE, related_name='table_restaurant', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associe')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['numero_table'],
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(default=uuid.uuid4, max_length=64, unique=True, verbose_name='Token de session')),
                ('django_session_key', models.CharField(max_length=40, unique=True, verbose_name='Cle de session Django')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_activite', models.DateTimeField(auto_now=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date du paiement')),
                ('est_active', models.BooleanField(default=True, verbose_name='Session active')),
                ('commande_payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_associee', to='commandes.commande', verbose_name='Commande payee')),
                ('table', models.ForeignKey(limit_choices_to={'role': 'Rtable'}, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Session de table',
                'verbose_name_plural': 'Sessions de tables',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TableToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name="Token d'authentification")),
                ('password_hash', models.CharField(max_length=128, verbose_name='Hash du mot de passe')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_utilisation', models.DateTimeField(blank=True, null=True)),
                ('table', models.OneToOneField(limit_choices_to={'role': 'Rtable'}, on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='Table associee')),
            ],
            options={
                'verbose_name': 'Token de table',
                'verbose_name_plural': 'Tokens de tables',
            },
        ),
    ]
