# Generated by Django 5.1 on 2026-06-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration de session'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='lat_connexion',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude de connexion'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='lng_connexion',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude de connexion'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='nb_echecs_gps',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'echecs GPS consecutifs"),
        ),
    ]
