# Generated by Django 5.1 on 2026-06-26 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_restaurant_reservation_delai_annulation_heures_and_more'),
        ('restaurant', '0003_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='duree_minutes',
            field=models.PositiveIntegerField(default=120, help_text='Durée attribuée selon le nombre de couverts (figée à la création)', verbose_name="Durée d'occupation (min)"),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('refusee', 'Refusée'), ('annulee', 'Annulée'), ('terminee', 'Terminée'), ('no_show', 'Absent (no-show)')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='ReservationClientBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(blank=True, default='', max_length=255, verbose_name='Raison')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'Rclient'}, on_delete=django.db.models.deletion.CASCADE, related_name='blocages_reservation', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_bloques', to='company.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Client bloqué (réservation)',
                'verbose_name_plural': 'Clients bloqués (réservation)',
                'unique_together': {('restaurant', 'client')},
            },
        ),
    ]
