# Generated by Django 5.1 on 2026-04-09 00:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0002_initial'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaisseComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Solde (GNF)')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Fermee')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ouverture")),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de fermeture')),
                ('motif_ecart', models.TextField(blank=True, null=True, verbose_name="Motif d'ecart a la fermeture")),
                ('montant_physique_fermeture', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montant physique a la fermeture')),
                ('comptable', models.ForeignKey(limit_choices_to={'role': 'Rcomptable'}, on_delete=django.db.models.deletion.CASCADE, related_name='caisses_comptables', to=settings.AUTH_USER_MODEL, verbose_name='Comptable')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caisses_comptables', to='company.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Caisse Comptable',
                'verbose_name_plural': 'Caisses Comptables',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CaisseGenerale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Solde actuel (GNF)')),
                ('solde_initial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Solde initial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caisse_generale', to='company.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Caisse Generale',
                'verbose_name_plural': 'Caisses Generales',
            },
        ),
        migrations.CreateModel(
            name='CaisseGlobale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ouverture', models.DateField(help_text='Automatiquement a 05h00 chaque jour', verbose_name="Date d'ouverture")),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Solde (GNF)')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Fermee')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de fermeture')),
                ('motif_ecart', models.TextField(blank=True, help_text='Obligatoire si ecart entre solde virtuel et montant physique', null=True, verbose_name="Motif d'ecart")),
                ('montant_physique_fermeture', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montant physique a la fermeture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fermee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caisses_globales_fermees', to=settings.AUTH_USER_MODEL, verbose_name='Fermee par')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caisses_globales', to='company.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Caisse Globale',
                'verbose_name_plural': 'Caisses Globales',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(help_text='Description de la depense (min 5 caracteres)', max_length=255, verbose_name='Motif')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('date_depense', models.DateField(verbose_name='Date de la depense')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('caisse_comptable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='paiements.caissecomptable', verbose_name='Caisse comptable')),
                ('enregistree_par', models.ForeignKey(limit_choices_to={'role': 'Rcomptable'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistree par')),
            ],
            options={
                'verbose_name': 'Depense',
                'verbose_name_plural': 'Depenses',
                'ordering': ['-date_depense'],
            },
        ),
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('approvisionnement', 'Approvisionnement'), ('depense', 'Depense')], max_length=20, verbose_name='Type de mouvement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant (GNF)')),
                ('motif', models.CharField(help_text='Description du mouvement (min 5 caracteres)', max_length=255, verbose_name='Motif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('caisse_comptable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='paiements.caissecomptable', verbose_name='Caisse comptable')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_caisse', to=settings.AUTH_USER_MODEL, verbose_name='Effectue par')),
            ],
            options={
                'verbose_name': 'Mouvement de caisse',
                'verbose_name_plural': 'Mouvements de caisse',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='commandes.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='RemiseServeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_virtuel', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant virtuel (attendu)')),
                ('montant_physique', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montant physique (recu)')),
                ('motif_ecart', models.TextField(blank=True, help_text='Obligatoire si montant physique != montant virtuel', null=True, verbose_name="Motif de l'ecart")),
                ('valide', models.BooleanField(default=False, verbose_name='Validee par comptable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caisse_globale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remises', to='paiements.caisseglobale', verbose_name='Caisse Globale')),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remise', to='paiements.paiement', verbose_name='Paiement associe')),
                ('serveur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remises_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Serveur')),
                ('validee_par', models.ForeignKey(blank=True, limit_choices_to={'role': 'Rcomptable'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remises_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validee par')),
            ],
            options={
                'verbose_name': 'Remise serveur',
                'verbose_name_plural': 'Remises serveurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
