# Generated by Django 5.1 on 2026-07-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='type_mouvement',
            field=models.CharField(choices=[('approvisionnement', 'Approvisionnement'), ('depense', 'Depense'), ('fermeture', 'Fermeture (transfert vers Caisse Generale)'), ('ecart', 'Ecart de caisse')], max_length=20, verbose_name='Type de mouvement'),
        ),
    ]
