# Generated by Django 5.1 on 2026-07-12 15:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_restaurant_livraison_lien_autorise_paiement'),
        ('paiements', '0002_alter_mouvementcaisse_type_mouvement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeApprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant demande (GNF)')),
                ('motif', models.CharField(max_length=255, verbose_name='Motif de la demande')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvee'), ('refusee', 'Refusee')], default='en_attente', max_length=12, verbose_name='Statut')),
                ('motif_refus', models.TextField(blank=True, null=True, verbose_name='Motif du refus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('caisse_comptable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_appro', to='paiements.caissecomptable', verbose_name='Caisse comptable')),
                ('demande_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_appro_creees', to=settings.AUTH_USER_MODEL, verbose_name='Demande par')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_appro', to='company.restaurant', verbose_name='Restaurant')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_appro_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validee/refusee par')),
            ],
            options={
                'verbose_name': "Demande d'approvisionnement",
                'verbose_name_plural': "Demandes d'approvisionnement",
                'ordering': ['-created_at'],
            },
        ),
    ]
