# Generated by Django 5.1 on 2026-08-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paiements", "0004_backfill_caisse_generale"),
    ]

    operations = [
        migrations.AddField(
            model_name="caissegenerale",
            name="date_initialisation",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date d'initialisation du solde"
            ),
        ),
    ]
