# Generated by Django 5.1 on 2026-03-22 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('menu', '0001_initial'),
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Session lors de laquelle cette commande a ete passee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_session', to='restaurant.tablesession', verbose_name='Session QR Code'),
        ),
        migrations.AddField(
            model_name='commande',
            name='table',
            field=models.ForeignKey(limit_choices_to={'role': 'Rtable'}, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='Table'),
        ),
        migrations.AddField(
            model_name='commandeitem',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commandes.commande', verbose_name='Commande'),
        ),
        migrations.AddField(
            model_name='commandeitem',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commande_items', to='menu.plat', verbose_name='Plat'),
        ),
        migrations.AddField(
            model_name='panieritem',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panier_items', to='menu.plat', verbose_name='Plat'),
        ),
        migrations.AddField(
            model_name='panieritem',
            name='table',
            field=models.ForeignKey(limit_choices_to={'role': 'Rtable'}, on_delete=django.db.models.deletion.CASCADE, related_name='panier_items', to=settings.AUTH_USER_MODEL, verbose_name='Table'),
        ),
        migrations.AlterUniqueTogether(
            name='commandeitem',
            unique_together={('commande', 'plat')},
        ),
        migrations.AlterUniqueTogether(
            name='panieritem',
            unique_together={('table', 'plat')},
        ),
    ]
