# Generated by Django 5.1 on 2026-06-24 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='cle_suivi',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Cle de suivi publique'),
        ),
        migrations.AddField(
            model_name='commande',
            name='client_adresse_livraison',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse de livraison'),
        ),
        migrations.AddField(
            model_name='commande',
            name='client_nom',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='client_telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone du client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('livraison', 'Paiement a la livraison'), ('orange_money', 'Orange Money'), ('mtn', 'MTN Mobile Money'), ('carte', 'Carte bancaire'), ('paydunya', 'PayDunya')], max_length=20, null=True, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='commande',
            name='type_commande',
            field=models.CharField(choices=[('sur_table', 'Sur table (QR)'), ('livraison', 'Livraison a domicile'), ('emporter', 'A emporter')], default='sur_table', max_length=20, verbose_name='Type de commande'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('prete', 'Prete'), ('en_livraison', 'En livraison'), ('servie', 'Servie / Livree'), ('payee', 'Payee')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='table',
            field=models.ForeignKey(limit_choices_to={'role__in': ['Rtable', 'Rclient']}, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='Table / Client'),
        ),
    ]
