# Generated by Django 5.1 on 2026-07-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_rclient_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='client_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude livraison'),
        ),
        migrations.AddField(
            model_name='commande',
            name='client_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude livraison'),
        ),
    ]
