# Generated by Django 5.1 on 2026-07-11 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_commande_client_latitude_commande_client_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivraisonToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_utilisation', models.DateTimeField(blank=True, null=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison_token', to='commandes.commande', verbose_name='Commande')),
                ('cree_par', models.ForeignKey(blank=True, help_text='Membre du staff responsable du lien (attribution du paiement)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraison_tokens_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Lien de livraison',
                'verbose_name_plural': 'Liens de livraison',
            },
        ),
    ]
