# Generated by Django 5.1 on 2026-07-23 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_livraisontoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='annulee_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Annulée le'),
        ),
        migrations.AddField(
            model_name='commande',
            name='annulee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_annulees', to=settings.AUTH_USER_MODEL, verbose_name='Annulée par'),
        ),
        migrations.AddField(
            model_name='commande',
            name='motif_annulation',
            field=models.TextField(blank=True, null=True, verbose_name="Motif d'annulation"),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('prete', 'Prete'), ('en_livraison', 'En livraison'), ('servie', 'Servie / Livree'), ('payee', 'Payee'), ('annulee', 'Annulee')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
    ]
