# Generated by Django 5.1 on 2026-08-06 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_commande_annulee_le_commande_annulee_par_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='table',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['Rtable', 'Rclient']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='Table / Client'),
        ),
    ]
