# Generated by Django 5.1 on 2026-04-09 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du restaurant')),
                ('email_admin', models.EmailField(help_text="Email de contact de l'admin du restaurant", max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name="Email de l'administrateur")),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Format valide: +224XXXXXXXXX ou XXXXXXXXX (9-20 chiffres)', regex='^\\+?[0-9]{9,20}$')], verbose_name='Telephone')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('is_active', models.BooleanField(default=True, help_text='Si False, tous les acces du restaurant sont bloques (suspension SaaS)', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Derniere modification')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['nom'],
            },
        ),
    ]
