# Generated by Django 5.1 on 2026-06-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_onboardingtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='duree_session_table',
            field=models.PositiveIntegerField(default=60, help_text="Duree maximale d'une session QR en minutes (30-120)", verbose_name='Duree session table (min)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude GPS'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude GPS'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rayon_connexion',
            field=models.PositiveIntegerField(default=200, help_text='Distance maximale en metres pour se connecter via QR Code', verbose_name='Rayon de connexion (m)'),
        ),
    ]
