# Generated by Django 5.1 on 2026-06-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_geo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='accept_emporter',
            field=models.BooleanField(default=False, help_text='Active la commande en ligne avec retrait sur place', verbose_name='Accepte les commandes a emporter'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='accept_livraison',
            field=models.BooleanField(default=False, help_text='Active la commande en ligne avec livraison a domicile', verbose_name='Accepte les commandes livraison'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='frais_livraison',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Laisser vide pour gratuit', max_digits=10, null=True, verbose_name='Frais de livraison (GNF)'),
        ),
    ]
