# Generated by Django 5.1 on 2026-06-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_rclient_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='reservation_delai_annulation_heures',
            field=models.PositiveIntegerField(default=2, help_text="Nombre d'heures avant l'heure de réservation jusqu'auquel le client peut annuler", verbose_name="Délai d'annulation (heures)"),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='reservation_validation_auto',
            field=models.BooleanField(default=True, help_text='Si True, la réservation est confirmée immédiatement ; sinon le staff valide manuellement', verbose_name='Validation automatique des réservations'),
        ),
    ]
