# Generated by Django 5.1 on 2026-07-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_restaurant_reservation_delai_annulation_heures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='livraison_lien_autorise_paiement',
            field=models.BooleanField(default=False, help_text='Autorise un livreur externe (lien / QR) à valider le paiement à la livraison', verbose_name='Encaissement via lien de livraison'),
        ),
    ]
