# Generated by Django 5.1 on 2026-08-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_frais_livraison_obsolete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="frais_livraison",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Obsolete : les frais sont convenus avec le livreur selon la distance.",
                max_digits=10,
                null=True,
                verbose_name="Frais de livraison (GNF) - obsolete",
            ),
        ),
    ]
